apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: mypod
    image: perl:5.34.0
    resources:
      limits:
        memory: 1Gi
        cpu: '1'
      requests:
        memory: 1Gi
        cpu: '1'
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
