apiVersion: batch/v1
kind: Job
metadata:
  name: batchtest
spec:
  template:
    spec:
      containers:
      - name: test
        image: ubuntu
        command:
        - "ls"
        args:
        - "/opt/pvc/"
        volumeMounts:
        - name: mypv
          mountPath: /opt/pvc
        resources:
          limits:
            memory: 8Gi
            cpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
      volumes:
      - name: mypv
        persistentVolumeClaim:
          claimName: testvol
      restartPolicy: "Never"
  backoffLimit: 2
